### ISSUE TITLE
Issues with passwords using special characters

### ISSUE THREAD

**Issue by matthiasamberg** [dwimberger/crowd-radius-server#3]
Hi,

we use crowd-radius server to authenticate OpenVPN against crowd. We have issues with users not being authenticated that have a too complex password (meaning, they use special chars (unfortunately I don't know which ones cause the issue). When they change their crowd passwords to only alphanumerical it all works fine. Could this be an issue with the crowd radius server? Any suggestions?

**Comment by dwimberger** [comment]
Hi there,

No really sure what causes the problem. Packet handling comes from tinyradius and Java generally handles Strings in UTF-8.

Did you try to build yourself and add debug logs? 

Specifically to check the output/encoding of:

```
  accessRequest.getUserName()
  accessRequest.getUserPassword()
```

If the issue is in tinyradius:
You may try to update the library to 1.0; see:
http://sourceforge.net/projects/tinyradius/files/TinyRadius%20Java%20Library/TinyRadius%201.0/
I currently don't have a test setup to verify it completely, but it compiles and may work without further modifications.

Regards,
Dieter

**Comment by matthiasamberg** [comment]
Hey thanks for your quick (!) reply.

I have looked further and there is a good chance that the issue is actually with the openVPN server itself. 
If this is not actually the case I will report back what I find with crowd-radius server.
I'm not sure I can close this issue but I guess it should be closed (at least for now)..

Thanks for your help!
